module.exports = {
  // 时间戳环境变量名称
  ENV_TIMESTAMP: 'ICES_VUE_CLI_PLUGIN_BUILDER_TIMESTAMP',
  // 编译事件
  EVENT_COMPILE: 'ICES_VUE_CLI_PLUGIN_BUILDER_EVENT_COMPILE',
  // 构建事件
  EVENT_BUILD: 'ICES_VUE_CLI_PLUGIN_BUILDER_EVENT_BUILD',
  // 插件：编译器事件
  PLUGIN_COMPILER_EVENT: 'ICES_VUE_CLI_PLUGIN_BUILDER_PLUGIN_COMPILER_EVENT',
}
