const PREFIX = 'ICES_VUE_CLI_PLUGIN_BUILDER'

module.exports = {
  // 时间戳环境变量名称
  ENV_TIMESTAMP: `${PREFIX}_TIMESTAMP`,
  // 编译事件
  EVENT_COMPILE_DONE: `${PREFIX}_EVENT_COMPILE_DONE`,
  // 构建事件
  EVENT_BUILD: `${PREFIX}_EVENT_BUILD`,
  // 插件默认注册名称
  PLUGIN_NAME_DEFAULT: `${PREFIX}_PLUGIN_DEFAULT_NAME`,
  // 插件：编译器事件
  PLUGIN_NAME_COMPILER_EVENT: `${PREFIX}_PLUGIN_COMPILER_EVENT`,
}
